poetry run python spliterxr.py ../rocky/col0.png col 0
poetry run python spliterxr.py ../rocky/col1.png col 1
poetry run python spliterxr.py ../rocky/col2.png col 2
poetry run python spliterxr.py ../rocky/col3.png col 3
poetry run python spliterxr.py ../rocky/col4.png col 4
poetry run python spliterxr.py ../rocky/col5.png col 5
poetry run python spliterxr.py ../rocky/image0.exr hgt 0
poetry run python spliterxr.py ../rocky/image1.exr hgt 1
poetry run python spliterxr.py ../rocky/image2.exr hgt 2
poetry run python spliterxr.py ../rocky/image3.exr hgt 3
poetry run python spliterxr.py ../rocky/image4.exr hgt 4
poetry run python spliterxr.py ../rocky/image5.exr hgt 5
poetry run python spliterxr.py ../rocky/norm_image0.png nor 0
poetry run python spliterxr.py ../rocky/norm_image1.png nor 1
poetry run python spliterxr.py ../rocky/norm_image2.png nor 2
poetry run python spliterxr.py ../rocky/norm_image3.png nor 3
poetry run python spliterxr.py ../rocky/norm_image4.png nor 4
poetry run python spliterxr.py ../rocky/norm_image5.png nor 5